repos:
  - repo: https://github.com/psf/black
    rev: 21.5b1
    hooks:
      - id: black
        args: [
          "fastapi_router_controller"
        ]
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.0.0
      hooks:
      - id: flake8